# Generated by Django 5.2.4 on 2025-08-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_alter_location_name_alter_product_flute_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True, verbose_name='車両番号')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ドライバー名')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='積載量（㎡）')),
                ('is_active', models.BooleanField(default=True, verbose_name='稼働中')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='配送日')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name=' 出発時間')),
                ('status', models.CharField(choices=[('unassigned', '未配車'), ('assigning', '配車中'), ('planned', '配車確定'), ('dispatched', '出荷済'), ('completed', '納品完了')], default='usassigned', max_length=20, verbose_name='ステータス')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem', verbose_name='対象注文明細')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.vehicle', verbose_name='車両')),
            ],
            options={
                'ordering': ['delivery_date', 'departure_time'],
            },
        ),
    ]
