# Generated by Django 5.2.4 on 2025-08-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryschedule',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='配送順'),
        ),
    ]
