# Generated by Django 5.2.4 on 2025-07-24 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_alter_order_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工程名')),
                ('code', models.CharField(max_length=20, verbose_name='工程コード')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squence', models.PositiveIntegerField()),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='orders.orderitem')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_plan.process')),
            ],
            options={
                'ordering': ['squence'],
            },
        ),
        migrations.CreateModel(
            name='ProductProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squence', models.PositiveIntegerField(verbose_name='工程順序')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_plan.process')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_process', to='orders.product')),
            ],
            options={
                'ordering': ['squence'],
                'unique_together': {('product', 'squence')},
            },
        ),
    ]
