# Generated by Django 5.2.4 on 2025-07-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemprocess',
            name='planned_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitemprocess',
            name='planned_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
