# Generated by Django 5.2.4 on 2025-07-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_location_name_alter_product_flute_type_and_more'),
        ('production_plan', '0002_alter_orderitemprocess_planned_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemprocess',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='productprocess',
            options={'ordering': ['sequence']},
        ),
        migrations.RenameField(
            model_name='orderitemprocess',
            old_name='squence',
            new_name='sequence',
        ),
        migrations.RenameField(
            model_name='productprocess',
            old_name='squence',
            new_name='sequence',
        ),
        migrations.AlterUniqueTogether(
            name='productprocess',
            unique_together={('product', 'sequence')},
        ),
        migrations.AlterField(
            model_name='productprocess',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_plan.process', verbose_name='工程名'),
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='予定日')),
                ('sequence', models.PositiveIntegerField(blank=True, null=True, verbose_name='工程順')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production_plan.process', verbose_name='工程')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product', verbose_name='製品')),
            ],
            options={
                'ordering': ['scheduled_date', 'sequence'],
                'unique_together': {('product', 'process', 'scheduled_date')},
            },
        ),
    ]
