# Generated by Django 5.2.4 on 2025-07-28 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0003_alter_orderitemprocess_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionschedule',
            options={'ordering': ('scheduled_date', 'order_item_process__sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='productionschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='order_item_process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production_plan.orderitemprocess', verbose_name='受注明細工程'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='process',
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productionschedule',
            name='sequence',
        ),
    ]
