# Generated by Django 5.2.4 on 2025-07-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0004_alter_productionschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionschedule',
            options={'ordering': ('scheduled_date', 'display_order')},
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
    ]
