# Generated by Django 5.2.4 on 2025-07-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0005_alter_productionschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemprocess',
            name='status',
            field=models.CharField(choices=[('pending', '未展開'), ('planning', '差立中'), ('completed', '指示作成')], default='pending', max_length=20, verbose_name='ステータス'),
        ),
    ]
