# Generated by Django 5.2.4 on 2025-07-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0006_orderitemprocess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemprocess',
            name='status',
            field=models.CharField(choices=[('pending', '未展開'), ('draft', '予定作成'), ('planning', '差立中'), ('completed', '指示作成')], default='pending', max_length=20, verbose_name='ステータス'),
        ),
    ]
