# Generated by Django 5.2.4 on 2025-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0007_alter_orderitemprocess_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemprocess',
            name='planned_end',
        ),
        migrations.AddField(
            model_name='orderitemprocess',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.DeleteModel(
            name='ProductionSchedule',
        ),
    ]
