# Generated by Django 5.2.4 on 2025-07-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plan', '0008_remove_orderitemprocess_planned_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemprocess',
            name='status',
            field=models.CharField(choices=[('pending', '未展開'), ('draft', '予定作成'), ('planning', '差立中'), ('complete', '指示作成')], default='pending', max_length=20, verbose_name='ステータス'),
        ),
    ]
