# Generated by Django 5.2.4 on 2025-08-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_alter_location_name_alter_product_flute_type_and_more'),
        ('production_plan', '0009_alter_orderitemprocess_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColgateScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_count', models.PositiveIntegerField(default=1, verbose_name='取数(丁取り)')),
                ('trim', models.PositiveIntegerField(default=0, verbose_name='トリム(mm)')),
                ('planned_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='貼合ｍ')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='反転')),
                ('order_item_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clgate_items', to='production_plan.orderitemprocess')),
            ],
            options={
                'ordering': ['order_item_process__display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('face', '表'), ('medium', '中芯'), ('liner', '裏')], max_length=20, verbose_name='層')),
                ('paper_type', models.CharField(max_length=50, verbose_name='原紙銘柄')),
                ('basis_wight', models.PositiveIntegerField(blank=True, null=True, verbose_name='坪量(g/m2)')),
                ('slit_width', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='紙巾(mm)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='orders.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
