# Generated by Django 5.2.4 on 2025-07-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_date_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(default=5235, max_length=20),
            preserve_default=False,
        ),
    ]
