# Generated by Django 5.2.4 on 2025-07-23 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customer_order_number',
            field=models.CharField(default=2222, max_length=20, unique=True, verbose_name='注文No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='納期'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='納入時間'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_type',
            field=models.CharField(choices=[('normal', '通常受注'), ('forecast', '見込受注'), ('confirmed', '出荷確定')], default='normal', max_length=10, verbose_name='受注区分'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='得意先コード'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='得意先名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='得意先'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.location', verbose_name='所属拠点'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='受注No'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='製品コード'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='製品名'),
        ),
        migrations.CreateModel(
            name='DeliveryDestinaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='届先名')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='届先コード')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='得意先')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.location', verbose_name='拠点')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.deliverydestinaion', verbose_name='届先'),
        ),
    ]
