# Generated by Django 5.2.4 on 2025-07-24 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to='orders.deliverydestinaion', verbose_name='届先'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customer_order_number',
            field=models.CharField(max_length=20, verbose_name='注文No'),
        ),
    ]
