# Generated by Django 5.2.4 on 2025-07-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='平米'),
        ),
        migrations.AddField(
            model_name='product',
            name='flow_direction',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='流れ寸法'),
        ),
        migrations.AddField(
            model_name='product',
            name='flute_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='フルート'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='完成寸法（高さ）'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='完成寸法（縦）'),
        ),
        migrations.AddField(
            model_name='product',
            name='slid_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='スリッタ寸法'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='完成寸法（横）'),
        ),
    ]
