# Generated by Django 5.2.4 on 2025-07-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_product_area_product_flow_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='拠点名'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flute_type',
            field=models.CharField(blank=True, choices=[('A', 'A段'), ('B', 'B段'), ('C', 'C段'), ('V', 'V段'), ('W', 'W段'), ('E', 'E段'), ('G', 'G段')], max_length=10, null=True, verbose_name='フルート'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.location', verbose_name='拠点'),
        ),
    ]
